version: "3"
services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: weight_wather
    ports:
      - 33061:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  es_data:
  mysql_data: